repositories:
 - name: ingress-nginx
   url: https://kubernetes.github.io/ingress-nginx
 - name: jenkins
   url:  https://charts.jenkins.io 
 - name: gitea
   url: https://dl.gitea.com/charts/
 - name: argo
   url: https://argoproj.github.io/argo-helm
 - name: sonarqube
   url: https://SonarSource.github.io/helm-chart-sonarqube

releases:

- name: ingress-nginx
  namespace: ingress
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.11.1
  values:
    - helm/nginx/values.yaml

- name: jenkins
  namespace: jenkins
  createNamespace: true
  chart: jenkins/jenkins
  version: 5.4.2
  values:
    - helm/jenkins/values.yaml

- name: gitea
  namespace: gitea
  createNamespace: true
  chart: gitea/gitea
  version: 10.4.0
  values:
    - helm/gitea/values.yaml

- name: argocd
  namespace: argocd
  createNamespace: true
  chart: argo/argo-cd
  version: 7.4.2
  values:
    - helm/argocd/values.yaml

- name: sonarqube
  namespace: sonarqube
  createNamespace: true
  chart: sonarqube/sonarqube
  version: 10.4.0+2288
  values:
    - helm/sonarqube/values.yaml
