repositories:
 - name: ingress-nginx
   url: https://kubernetes.github.io/ingress-nginx
 - name: jenkins
   url:  https://charts.jenkins.io 
#  - name: gitea
#    url: https://dl.gitea.com/charts/

releases:

- name: ingress-nginx
  namespace: ingress
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.11.1
  values:
    - helm/ingress/values.yaml

- name: jenkins
  namespace: jenkins
  createNamespace: true
  chart: jenkins/jenkins
  version: 5.4.2
  values:
    - helm/jenkins/values.yaml

# - name: gitea
#   namespace: gitea
#   createNamespace: true
#   chart: gitea/gitea
#   version: 10.3.0
#   values:
#     - helm/gitea/values.yaml

    ##